version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: ampl/doc/source/conf.py

python:
   install:
   - requirements: ampl/doc/requirements.txt